### ISSUE TITLE
only generate current school year school_buildings

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/ceqr-app-data-archive#10]
```
SCHOOL_YEAR = f'{datetime.date.today().year-1}-{datetime.date.today().year}'
print(f'current school year is {SCHOOL_YEAR}')
```

**Comment by baolingz** [comment]
@SPTKL could you explain this issue in more detail?

**Comment by SPTKL** [comment]
In the ceqr app, we only need to deliver the school buildings for each school year, currently we are computing all school years, note how in ceqr app database, there are only 9 records for lcgms.2018, because we only need the records for that school year

When you are doing dataloading, you should load data from source, 
https://www.nycenet.edu/PublicApps/LCGMS.aspx
instead of the ceqr db

Once you load the complete dataset into recipes, everytime we run a build, 
the python script should look like: 
```
pd.read_sql('SELECT * FROM doe_lcgms."2019/09/27" WHERE school_year={school_year}', con = recipe_engine)
```
