### ISSUE TITLE
CEQR source data - schools

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/ceqr-app-data-archive#12]
@pichot @mshapiro1 
Could you share with us the raw inputs for the following three datasets which are in the `ceqr_data`? 
- [x] `doe_lcgms`
- [x] `sca_bluebook`
- [x] `doe_school_subdistricts`
- [x] `sca_enrollment_pct_by_sd `
- [x] `sca_enrollment_projections_by_sd`

Ideally, we should be able to load all these datasets from a csv or url into our `recipe_data`

Thank you!

**Comment by SPTKL** [comment]
@baolingz 
+ `lcgms` https://www.nycenet.edu/PublicApps/LCGMS.aspx
+ `bluebook`https://gitlab.com/nycplanning/ceqr-app-data/blob/master/data-packages/public-schools/public-schools-2018/data/bluebook.csv

**Comment by baolingz** [comment]
@SPTKL @pichot 

- `lcgms` the open data does not have `org_level`, `school_year`,  `pe`, `ie` and `he` fields which are available in `ceqr_data`. We need to know the logic to generate those fields.
-  `bluebook` this data is private in Gitlab. We would like to know where this data comes from originally.

**Comment by SPTKL** [comment]
@baolingz we will receive bluebook from @mshapiro1  in the future, take it from gitlab for now

**Comment by SPTKL** [comment]
+ elementary school and middle school boundaries @mshapiro1 
+ sca housing pipeline (aka known projects database) --> ceqr more granular

Cora -> sca capital planning
Johnathan -> doe office of district planning ( school districts, changing proposals)
