### ISSUE TITLE
CEQR Air Quality: Atypical Roadway

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#17]
What is an Atypical Roadway?  A roadway that is either elevated or depressed compared to the surrounding environment.  Not on the same level.  If site is 200 feet from an Atypical Roadway then this needs to be considered in the analysis.

- [x] Determine best source for extracting Atypical Roadways (LION, Planimetrics, or...?) 
- [x] Publish subset of data
- [ ]  Create line dataset (convert to roadbed?)

**Comment by SPTKL** [comment]
https://github.com/CityOfNewYork/nyc-planimetrics/blob/master/Capture_Rules.md
Seems like this is something we can potentially extract from `planimetrics`
![image](https://user-images.githubusercontent.com/13207770/65520437-8eef3900-deb5-11e9-854e-dee33254a28e.png)
![image](https://user-images.githubusercontent.com/13207770/65520552-be9e4100-deb5-11e9-8a28-17e612868154.png)
we can also use the elevation points together with feature code to determine elevated/depressed roadways?
https://data.cityofnewyork.us/Transportation/Elevation-points/szwg-xci6/data

**Comment by SPTKL** [comment]
cscl has roadway type: and we can pull it from Open data
![image](https://user-images.githubusercontent.com/13207770/66403478-a1d53380-e9b4-11e9-8db5-205a112c410a.png)
https://github.com/CityOfNewYork/nyc-geo-metadata/blob/master/Metadata/Metadata_StreetCenterline.md

**Comment by SPTKL** [comment]
By definition of atypical roadways: 
https://www1.nyc.gov/assets/oec/technical-manual/17_Air_Quality_2014.pdf __page 19__
> Projects that would result in placement of operable windows (i.e., windows that may be opened and closed by the tenant), balconies, air intakes, or intake vents generally within 200 feet of an atypical (e.g., not at-grade) source of vehicular pollutants, such as a highway or bridge with a total of more than two lanes.

**Comment by SPTKL** [comment]
cscl has grade level for street centerlines (for each stretch, the grade level of 'from' and 'to')
![image](https://user-images.githubusercontent.com/13207770/66404337-4146f600-e9b6-11e9-8420-e3a51026e76a.png)

**Comment by SPTKL** [comment]
```sql
WITH lion as (
select distinct physicalid::text, nullif(number_total_lanes, '  ')::numeric as number_total_lanes
	from dcp_lion.latest
), cscl_filtered as (
	select *
	from cscl.latest 
	where FRM_LVL_CO!= '13' or TO_LVL_CO!= '13'
), atypical as (
	SELECT full_stree, physicalid, st_width, 
		r_zip, l_zip, borocode, FRM_LVL_CO, TO_LVL_CO,
		number_total_lanes, wkb_geometry 
FROM cscl_filtered left join lion USING (physicalid))
SELECT full_stree, max(number_total_lanes) as number_of_lanes, st_union(wkb_geometry) 
FROM atypical group by full_stree;
```
or 
```sql
WITH lion as (
select distinct physicalid::text, nullif(number_total_lanes, '  ')::numeric as number_total_lanes
	from dcp_lion.latest
), cscl_filtered as (
	select *
	from cscl.latest 
	where FRM_LVL_CO!= '13' or TO_LVL_CO!= '13'
)SELECT full_stree, physicalid, st_width, 
		r_zip, l_zip, borocode, FRM_LVL_CO, TO_LVL_CO,
		number_total_lanes, wkb_geometry 
FROM cscl_filtered left join lion USING (physicalid);
```
note that the first code block has an aggregation by street name, therefore, some of the more granular information such as grade level, zipcode street widths are lost. We can find those info in the second code block.

```
ogr2ogr -f "ESRI Shapefile" <file_name>.csv PG:"<pg info here>" -sql "<sql statement here>" 
```

**Comment by SPTKL** [comment]
Note that we didn't filter by the number of lanes, some segments have number of lanes missing, this needs review
https://gist.github.com/SPTKL/afdb70a12094aafbbb0b9ac7eff3811f

**Comment by baolingz** [comment]
- [x] Remove non-vehicular roads – pedestrian overpasses and bike paths **priority**
- [ ] Once EARD has verified that we’ve identified the right roads, create buffers

**Comment by baolingz** [comment]
```
        SELECT street AS streetname, segmentid, streetwidth_min,streetwidth_max, 
            lzip AS left_zipcode, rzip AS right_zipcode,
            LEFT(StreetCode, 1) AS borocode, nodelevelf, nodelevelt,
            featuretyp, trafdir, nullif(number_total_lanes, '  ')::NUMERIC AS number_total_lanes, 
            trim(bikelane) AS bikelane, wkb_geometry AS geom
        FROM {input_table}
        WHERE ((nodelevelf!= 'M' AND nodelevelf!= '*' AND nodelevelf!= '$')
        OR (nodelevelt!= 'M' AND nodelevelt!= '*' AND nodelevelt!= '$'))
        AND trafdir != 'P'
        AND (nullif(number_total_lanes, '  ')::NUMERIC != 1
        OR nullif(number_total_lanes, '  ')::NUMERIC IS NULL)
        AND trim(bikelane) != '1'
        AND trim(bikelane) != '2'
        AND trim(bikelane) != '4'
        AND trim(bikelane) != '9';
 ```
