### ISSUE TITLE
CEQR Air Quality: Areas of Concern (shapefiles)

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#18]
Work with EARD to  generate more accurate maps of:
- [ ] Downtown Brooklyn
- [ ] Long Island City
- [ ] Manhattan (details in technical manual)

**Comment by AmandaDoyle** [comment]
- [x] EARD will send paper maps to DE
- [ ]  EDM will digitize

**Comment by AmandaDoyle** [comment]
[CEQR Tech Manual Air_Quality_Area of Concern Map.pdf](https://github.com/NYCPlanning/ceqr-app-data/files/3654342/CEQR.Tech.Manual.Air_Quality_Area.of.Concern.Map.pdf)
For downtown Brooklyn and Long Island City, Queens, please see attached

For Manhattan between 30th and 61st Street, there’s no map and we assume it’s the entire area bounded by 30th and 61st.

**Comment by SPTKL** [comment]
ready for review
https://gist.github.com/SPTKL/62618b6cc44ce7b9a52c9896df95e53d
