### ISSUE TITLE
CEQR Air Quality: Ventilation Outlets

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#19]
DOT data for ventilation outlets

- [x] Identify source data
This refers to the tunnel ventilation towers for the 4 major vehicle tunnels in NYC (Midtown, Lincoln, Holland, Hugh L. Carey Tunnel aka Battery)
- [x] Create a spatial dataset of the vents on either side of the tunnel

**Comment by baolingz** [comment]
@AmandaDoyle ready to review
https://gist.github.com/baolingz/396075390b455ddd6e6af599940fc636
