### ISSUE TITLE
doe_bluebook and doe_lcgms merge

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/ceqr-app-data-archive#2]
https://gitlab.com/nycplanning/ceqr-app-data/issues/5
Currently, we provide schools data in two schemas on CEQR Data: `doe_lcgms` and `sca_bluebook`. This does not make intuitive sense on the app side, as these are just sources for the ultimate need of the app: a row representing one school.

This new schema would be named something like `ceqr_school_buildings` and look like:

```sql
CREATE TABLE ceqr_school_buildings."2017" (
    district integer,
    subdistrict integer,
    borocode integer,
    bldg_name character varying,
    excluded boolean,
    bldg_id character varying,
    org_id character varying,
    org_level character varying,
    name character varying,
    address character varying,
    ps_capacity integer,
    ps_enroll integer,
    is_capacity integer,
    is_enroll integer,
    hs_capacity integer,
    hs_enroll integer,
    source text, -- either 'bluebook' or 'lcgms'
    geom geometry(Point,4326)
);
```
This table would replace `bluebook` and `lcgms` tables in the app moving forward. The yearly data generation task would be to combine bluebook and lcgms to provide the most accurate list of schools open in the current school year, with their enrollments and capacities.

- [x] load both datasets into RECIPE_ENGINE
- [x] change column names for sensitive info
- [x] create build.py to merge the two

**Comment by baolingz** [comment]
still waiting for the `lcgms` from doe to finalize the script
