### ISSUE TITLE
CEQR Air Quality: Garages

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#20]
Garages

- Sanitation
- School Buses
- MTA bus garages
- Uses Transportation trigger (> 85 spaces ?)

Tie to improvement of FacDB

**Comment by AmandaDoyle** [comment]
Lynn is going to filter FacDB and provide file to Adrien to include

**Comment by AmandaDoyle** [comment]
@aferrar 
Need to set up a group lyr file, with different symbologies by factype so that EARD can easily see what’s available

**Comment by aferrar** [comment]
10/21/2019
Set up new group lyr file with different symbologies by fac sub-group. Available on M drive CEQR directory
