### ISSUE TITLE
CEQR Air Quality: Ambient Air Quality

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#21]
Source data
[State has stations monitoring air quality](https://www.dec.ny.gov/chemical/8536.html)

- [x] Understand how source data are used
- [x] If it's determined to be useful, build data pipeline

**Comment by AmandaDoyle** [comment]
- [x] Find or create layer of air monitoring stations (see data below)
- [ ] Find tabular data on yearly air quality reports and tie tabular data to spatial data
- [ ] Build pipeline so that data can easily be added with each year's update

**Comment by SPTKL** [comment]
monitoring stations map
https://data.ny.gov/Energy-Environment/Air-Monitoring-Station-Locations-Attributes-Map/ekga-4wdn
this might need manual data entry

**Comment by AmandaDoyle** [comment]
Add fields to indicate what is being monitored at each station.  Can be manual data entry since they don't need the actual readings

**Comment by baolingz** [comment]
@AmandaDoyle Can I close this issue?
