### ISSUE TITLE
CEQR Air Quality: DOT Traffic Cameras

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#27]
Add URL field that links to traffic camera for that location

**Comment by SPTKL** [comment]
[dot_traffic_cameras.zip](https://github.com/NYCPlanning/ceqr-app-data/files/3709473/dot_traffic_cameras.zip)

**Comment by AmandaDoyle** [comment]
For @aferrar 
There’s a way to add a clickable link to an ESRI table. This should be done for the url field

**Comment by aferrar** [comment]
10/21/2019
URL field hyperlinks have been added to data set and associated layer file. ArcGIS does not have functionality for directing to url from directly within the attribute table but links are direct-able when viewing individual feature attributes / by using the identify tool:

**Hyperlink not available through attribute table**
![image](https://user-images.githubusercontent.com/11024203/67235854-f4333d00-f415-11e9-8ae1-2af81535dcea.png)

**Hyperlink available through properties/identify tool**
![image](https://user-images.githubusercontent.com/11024203/67235942-2e9cda00-f416-11e9-875b-77d30fed263a.png)
