### ISSUE TITLE
Add metadata for Air datasets

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/ceqr-app-data-archive#31]
Work with GIS to determine what template to use and generate metadata

**Comment by aferrar** [comment]
**Updated 10/23/2019**

Hi all, see below for a breakdown of what CEQR Air metadata currently does and doesn't exist within the network gdb. Please let me know where any missing meta info can be pulled from

Air Data sets Metadata Breakdown 
**(o - indicates meta info exists in gdb/layer ; x - indicates meta info is missing from gdb/layer)**:

| Data set Name | Summary | Description | Credits | Tags | Field Descriptions |
|-------|----------|---|---|---|---|
| Areas of Concern | x | x | x | x | o |
| Atypical Roadways | x | x | x | x | x |
| DEP CATS Permits | o | o | o | o | o |
| DOT Traffic Cameras   | o | o | o | o | o |
| Facilities Garages | x | x | x | x | x |
| NYSDEC Air Monitoring Stations | x | x | x | x | x |
| NYSDEC Facility Permits | o | o | o | o | o | o | o | o |
| NYSDOT Average Annual Daily Traffic (AADT) | o | o | o | o | o |
| NYSDOT Functional Class | o | o | o | o | x |
| NYSDOT Traffic Tables (2015 - 2017) | x | x | x | x | o |
| Tunnel Ventilation Towers | o | o | o | o | o |

**Comment by baolingz** [comment]
NYSDEC Facility Permits 
- We merged the datasets of title v and state permits together, deduplicate and geocode them.
- https://data.ny.gov/Energy-Environment/Issued-Title-V-Facility-Permits/4n3a-en4b
- https://data.ny.gov/Energy-Environment/Issued-State-Facility-Air-Permits/2wgt-bc53

Tunnel Ventilation Towers
- This refers to the tunnel ventilation towers for the 4 major vehicle tunnels in NYC (Midtown, Lincoln, Holland, Hugh L. Carey Tunnel aka Battery)
- No official source data, geometry points were labeled by visually identifying tunnel ventilation towers from Google Maps. We created a spatial dataset of the vents on either side of the tunnel.

DEP CATS Permits
- https://data.cityofnewyork.us/Environment/CATS-Permits/f4rp-2kvy

**Comment by baolingz** [comment]
@aferrar 
Areas of Concern
- Work with EARD to generate more accurate maps of:
  - Downtown Brooklyn
  - Long Island City
  - Manhattan (details in technical manual)

Atypical Roadways:
- A roadway that is either elevated or depressed compared to the surrounding environment. 
- This dataset is created by extracting roadways from the LION Single Line Street Base Map, which are above or below ground level excluding non-vehicle roads, such as pedestrian overpasses and bike paths.

Facilities Garages: 
- This dataset is created by extracting facilities from the facilities database, which are under the 'Core Infrastructure and Transportation' domain as well as under the 'Maintenance and Garages' subgroup from the 'Administration of Government' domain.

NYSDEC Air Monitoring Stations
- https://data.ny.gov/Energy-Environment/Air-Monitoring-Station-Locations-Attributes/qcpj-zdb6

NYSDOT Traffic Tables (2015 - 2017)
- https://www.dot.ny.gov/divisions/engineering/technical-services/highway-data-services/hdsb
