### ISSUE TITLE
Apply Standard data schema on Air Datasets

### ISSUE THREAD

**Issue by baolingz** [NYCPlanning/ceqr-app-data-archive#32]
Standard data schema: https://docs.google.com/spreadsheets/d/1Z41fgiU_mi1KltlS783kUZpPcC8Sn7hUxTqhaNxQFg8/edit?pli=1#gid=0

- [x] `dep_cats_permits`: update `borough` values to proper case, add `geo_` to all fields return by geosupport, geometry-->geom, expirationdate::date, issuedate::date, add `geo_address`, (geo_latitude,geo_longitude)::double precision
- [x] `nysdec_facility_permits`: add `geo_` to all fields return by geosupport, geometry-->geom, , issue_date::date, expire_date::date
- [x] `dot_traffic_cameras`: geometry-->geom
- [x] `atypical_roadways`: l_zip-->left_zipcode, r_zip-->right_zipcode
- [x] `facilities_garages`: add `geo_` to all fields return by geosupport, geometry-->geom
- [x] `nysdec_air_monitoring_stations`: geometry-->geom, (Add `geo_` in front of longitude, latitude if they are from geosupport), map county-->borough (remove outsiteNYC by setting region='2'), borocode::integer, (geo_latitude,geo_longitude, geo_x_coord, geo_y_coord)::double precision
- [x] `nysdot_functional_class`: geometry-->geom
- [x] `nysdot_aadt`: geometry-->geom
- [x] `nysdot_traffic_counts`: should we rename county_code to borocode and remove records outside NYC?

**Comment by AmandaDoyle** [comment]
@baolingz the changes outlined above are right
this issue relates to the notes in other issue (i.e. removing the geosupport return code field)
Yes, for 'nysdot_traffic_counts' I'd remove records outside NYC, rename county_code to borocode, and map county_code values to borocode values
