### ISSUE TITLE
Improve Geocoding / address cleanup for DEP air quality permits

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#45]
- [x] 1. Where GRC code or GRC code 2 is 42 or 41, output subset of records and send to GRU, because addresses may be missing in PAD
- [x] 2. Add keywords such as `Cross` and `Crs` to geocoding intersection function
- [x] 3. Update `JFK international airport` so that it gets a hit from Geosupport
- [ ] 4. Explore on-to-from formats and build out function in Geocoding suite
- [ ] 5. Where reason code is EE data engineering will fix addresses if it's clear what it should be

If any component of the address is missing (house number (i.e. 13B), street name, borough) we cannot fix the address 
Do not fix addresses where the error code indicates there is an extra hyphen (GRC 13 3)
Most likely cannot fix addresses where GRC = 13

**Comment by baolingz** [comment]
```
-- number of records where GRC code or GRC code 2 is 42 or 41
-- 818
SELECT * FROM dep_cats_permits.geo_rejects
WHERE geo_grc = '42' OR geo_grc = '41'
OR geo_grc2 = '42' OR geo_grc2 = '41'
;
```
