### ISSUE TITLE
Mismatch in the number of DEP CATS permits

### ISSUE THREAD

**Issue by CliangDCP** [NYCPlanning/ceqr-app-data-archive#47]
Please investigate the number of DEP CATS permits comparing to what EARD has purged with the following categories:

- All Cancelled permits
- All G-prefix permits
- All C-prefix + Registration (including Registration, Boiler Registration II, and Registration Inspection)
- All CA-Prefix + Work Permit + Expired permits

[CATS Permits raw 010720.zip](https://github.com/NYCPlanning/ceqr-app-data/files/4130483/CATS.Permits.raw.010720.zip)

**Comment by baolingz** [comment]
@CliangDCP Thanks for pin us on this. We've already figured out what made the discrepancies happen for the DEP CATS permits dataset and fixed the ETL scripts but we are still trying to improve its geocoding performance by addressing [issues 45 ](https://github.com/NYCPlanning/ceqr-app-data/issues/45). We will ship you the latest version by the end of the week. Feel free to pin us if you have any other questions.

**Comment by CliangDCP** [comment]
Got it, thank you!

**Comment by baolingz** [comment]
```
SELECT COUNT(*) FROM dep_cats_permits.latest
WHERE TRIM(status) != 'CANCELLED'
AND LEFT(applicationid, 1) != 'G'
AND (LEFT(applicationid, 1) != 'C' OR (requesttype != 'REGISTRATION' AND requesttype != 'REGISTRATION INSPECTION' AND requesttype != 'BOILER REGISTRATION II'))
AND (LEFT(applicationid, 2) != 'CA' OR requesttype != 'WORK PERMIT' OR TRIM(status) != 'EXPIRED')
;
```
