### ISSUE TITLE
Create sca_e_projections by boro

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#56]
Aggregate HS data to boro level
1. Create a new folder named `sca_e_projections_by_boro` under the `ceqr_app_date/ceqr/recipes` directory
2. Create config.json, README.md, build.py, and requirements.txt
3. use `sca_e_projections.2019` as the input data
4. target schema @bfreeds please confirm the schema for this CEQR table
```
CREATE TABLE sca_e_projections_by_boro."2019" (
    school_year integer,
    borocode integer,
    hs integer
);
```
5. build its ETL pipeline using [sca_e_projections](https://github.com/NYCPlanning/ceqr-app-data/blob/master/ceqr/recipes/sca_e_projections/build.py) as an example
    - convert the input table from a wide table to a long table using a pandas syntax called `melt`
    - calculate the hs projections by summing up `projected` = [9,10,11,12], don't use `projected` =  '9-12 Total' from `sca_e_projections.2019` which has incorrect values
    - write a python function or dictionary to map `district` to its matching`borocode`
    - aggregate the data to boro level
6. export the output to `EDM_DATA`
7. push your code to another branch

**Comment by bfreeds** [comment]
@AmandaDoyle following the schemas for 2017 and 2018 would be:
```sql
CREATE TABLE sca_enrollment_projections_by_boro."2019" (
    year varchar,
    borough text,
    hs integer
);
```

**Comment by baolingz** [comment]
@bfreeds @AmandaDoyle We've refactored the ETL for 2018 and 2019 tables based on the above schema using SCA's source data.

**Comment by bfreeds** [comment]
@baolingz copy, thank you!  Apologies for my delayed response, Github's new notifications management (which is waaay more usable) helped me see that I was pinged on this issue.
