### ISSUE TITLE
Air: Update filter for DEP dataset

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#79]
Remove the following records from the DEP Permits dataset
- All Cancelled permits (no change)
- All G-prefix permits (no change)
- All C-prefix permits (change)
- All P-prefix permits with Registration (including Registration, Boiler Registration II, and Registration Inspection) (change)

**Comment by mgraber** [comment]
``` sql
SELECT * FROM dep_cats_permits.latest
WHERE TRIM(status) != 'CANCELLED'
AND LEFT(applicationid, 1) != 'G'
AND LEFT(applicationid, 1) != 'C'
AND NOT (LEFT(applicationid, 1) = 'P'
    AND (requesttype = 'REGISTRATION'
    OR requesttype = 'REGISTRATION INSPECTION'
    OR requesttype = 'BOILER REGISTRATION II'));
```

Filtering out cases where `LEFT(applicationid, 1) = 'C'` might need to happen after geocoding if the review subset in #80 needs to be geocoded.
