### ISSUE TITLE
Air: DEP data subset for research

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/ceqr-app-data-archive#80]
Create subset of DEP dataset that contains only C-prefix permits with Certificate to Operate for research

**Comment by mgraber** [comment]
@AmandaDoyle Is this a subset of the source data or of the geocoded data?

**Comment by mgraber** [comment]
```sql
SELECT * FROM dep_cats_permits.latest
WHERE LEFT(applicationid, 1) = 'C'
AND requesttype = 'CERTIFICATE TO OPERATE';
```
With 2019/09/24 data, the subset for review has 24044 records.

**Comment by AmandaDoyle** [comment]
subset of the source data

**Comment by mgraber** [comment]
For now, extract this subset from recipes with a query. Not needed in code yet.
